

seed: 42
##### DATASET PARAMETERS
source_language:
  name: English
  dataset_path: "./Datasets/it-en/europarl-v7.it-en.en"

target_language:
  name: Italian
  dataset_path: "./Datasets/it-en/europarl-v7.it-en.it"

maximum_dataset_lenght: 50000

###### ENCODER
encoder:
  vocab_size: 10000
  num_layers: 1
  ff_hidden_size: 256


#### DECODER
decoder:
  vocab_size: 10000
  num_layers: 1
  ff_hidden_size: 256

#### BOTH
same_source_target_vocabulary: False
embedding_size: 16
num_heads: 1
ignore_index: None

### TRAINING CONFIG
checkpoint_dir: "./checkpoints"
logs_dir: "./logs"
from_checkpoint: True
train: False
test: True

max_epochs: 1
lr: 1e-3
label_smoothing: 0.1
with_scheduler: False
batch_size: 6
dropout: 0.1
warmup_steps: 4000
